### ISSUE TITLE
Unable to add second car

### ISSUE THREAD

**Issue by ptath** [abdusalamov/homebridge-starline#2]
```
[2019-2-1 19:02:49] Loading 3 platforms...
[2019-2-1 19:02:49] [Config] Initializing config platform...
[2019-2-1 19:02:49] [Config] Spawning homebridge-config-ui-x with PID 1103
[2019-2-1 19:02:49] [ZigBee] Initializing ZigBeePlatform platform...
[2019-2-1 19:02:49] [ZigBee] ZigBee platform initialization
[2019-2-1 19:02:49] [StarlinePlatform] Initializing StarlinePlatform platform...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Car Online'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Двигатель'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Сигнализация'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Охрана'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Напряжение сети'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Температура салона'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Двери'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Температура двигателя'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Капот'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Багажник'...
[2019-2-1 19:02:50] [StarlinePlatform] Initializing platform accessory 'Car Online'...
Uncaught Exception Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: eea4652c-0691-46c3-ae00-78da6b7e6377
    at Bridge.Accessory.addBridgedAccessory (/opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:266:13)
    at Server.<anonymous> (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:399:24)
    at /opt/nodejs/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at StarlinePlatform.accessories (/opt/nodejs/lib/node_modules/homebridge-starline/src/StarlinePlatform.js:41:5)
    at Server._loadPlatformAccessories (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:386:20)
    at Server._loadPlatforms (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:330:16)
    at Server.run (/opt/nodejs/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/opt/nodejs/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/opt/nodejs/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
```

**Comment by abdusalamov** [comment]
@ptath Thank you for report! Please attach your config without username and password

**Comment by ptath** [comment]
here it is ) [копия config-субара и сузука не работает.txt](https://github.com/abdusalamov/homebridge-starline/files/2822222/config-.txt)
